// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeyBaterias.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeyBaterias.Infrastructure.Migrations
{
    [DbContext(typeof(NeyBateriasDbContext))]
    [Migration("20260716030820_TornarCamposClienteOpcionais")]
    partial class TornarCamposClienteOpcionais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateOnly>("DataCadastro")
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro");

                    b.HasKey("IdCliente")
                        .HasName("pk_cliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ClienteFisico", b =>
                {
                    b.Property<int>("IdClienteFisico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente_fisico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClienteFisico"));

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdClienteFisico")
                        .HasName("pk_cliente_fisico");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_fisico_cpf");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_fisico_id_cliente");

                    b.ToTable("cliente_fisico", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ClienteJuridico", b =>
                {
                    b.Property<int>("IdClienteJuridico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente_juridico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClienteJuridico"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Ie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ie");

                    b.Property<string>("ImTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("im_telefone");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("TelCelular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tel_celular");

                    b.HasKey("IdClienteJuridico")
                        .HasName("pk_cliente_juridico");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_juridico_cnpj");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_juridico_id_cliente");

                    b.ToTable("cliente_juridico", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.CompraReposicao", b =>
                {
                    b.Property<int>("IdReposicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reposicao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReposicao"));

                    b.Property<DateTime>("DataReposicao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_reposicao");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("integer")
                        .HasColumnName("id_fornecedor");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.HasKey("IdReposicao")
                        .HasName("pk_compra_reposicao");

                    b.HasIndex("IdFornecedor")
                        .HasDatabaseName("ix_compra_reposicao_id_fornecedor");

                    b.ToTable("compra_reposicao", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ConfiguracaoEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_empresa");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_configuracao_empresa");

                    b.ToTable("configuracao_empresa", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "",
                            Email = "",
                            Endereco = "",
                            NomeEmpresa = "NeyBaterias",
                            Telefone = ""
                        });
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Estoque", b =>
                {
                    b.Property<int>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estoque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstoque"));

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimento");

                    b.Property<int?>("IdItemReposicao")
                        .HasColumnType("integer")
                        .HasColumnName("id_item_reposicao");

                    b.Property<int?>("IdItemVenda")
                        .HasColumnType("integer")
                        .HasColumnName("id_item_venda");

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.Property<int>("QtdMovimento")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_movimento");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_movimento");

                    b.HasKey("IdEstoque")
                        .HasName("pk_estoque");

                    b.HasIndex("IdItemReposicao")
                        .IsUnique()
                        .HasDatabaseName("ix_estoque_id_item_reposicao");

                    b.HasIndex("IdItemVenda")
                        .IsUnique()
                        .HasDatabaseName("ix_estoque_id_item_venda");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("ix_estoque_id_produto");

                    b.ToTable("estoque", null, t =>
                        {
                            t.HasCheckConstraint("CK_Estoque_OrigemUnica", "(id_item_venda IS NOT NULL AND id_item_reposicao IS NULL) OR (id_item_venda IS NULL AND id_item_reposicao IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.FormaPagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pagamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPagamento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.HasKey("IdPagamento")
                        .HasName("pk_forma_pagamento");

                    b.ToTable("forma_pagamento", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fornecedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFornecedor"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contato");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endereco");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdFornecedor")
                        .HasName("pk_fornecedor");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedor_cnpj");

                    b.ToTable("fornecedor", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItem"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdItem")
                        .HasName("pk_item");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ItemReposicao", b =>
                {
                    b.Property<int>("IdItemReposicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_item_reposicao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItemReposicao"));

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.Property<int>("IdReposicao")
                        .HasColumnType("integer")
                        .HasColumnName("id_reposicao");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_compra");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.HasKey("IdItemReposicao")
                        .HasName("pk_item_reposicao");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("ix_item_reposicao_id_produto");

                    b.HasIndex("IdReposicao")
                        .HasDatabaseName("ix_item_reposicao_id_reposicao");

                    b.ToTable("item_reposicao", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<int>("IdItemVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_item_venda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItemVenda"));

                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<int>("IdVenda")
                        .HasColumnType("integer")
                        .HasColumnName("id_venda");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_venda");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.HasKey("IdItemVenda")
                        .HasName("pk_item_venda");

                    b.HasIndex("IdItem")
                        .HasDatabaseName("ix_item_venda_id_item");

                    b.HasIndex("IdVenda")
                        .HasDatabaseName("ix_item_venda_id_venda");

                    b.ToTable("item_venda", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Operador", b =>
                {
                    b.Property<int>("IdOperador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_operador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOperador"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("login");

                    b.Property<int>("NivelAcesso")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_acesso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sobrenome");

                    b.Property<string>("TelCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tel_celular");

                    b.HasKey("IdOperador")
                        .HasName("pk_operador");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_operador_email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_operador_login");

                    b.ToTable("operador", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Amperagem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("amperagem");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_custo");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_venda");

                    b.HasKey("IdProduto")
                        .HasName("pk_produto");

                    b.HasIndex("IdItem")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_id_item");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Servico", b =>
                {
                    b.Property<int>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_servico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdServico"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco");

                    b.Property<int>("TempoEstimado")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_estimado");

                    b.HasKey("IdServico")
                        .HasName("pk_servico");

                    b.HasIndex("IdItem")
                        .IsUnique()
                        .HasDatabaseName("ix_servico_id_item");

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_venda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenda"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_venda");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("desconto");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdOperador")
                        .HasColumnType("integer")
                        .HasColumnName("id_operador");

                    b.Property<int>("IdPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_pagamento");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_total");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_venda");

                    b.HasKey("IdVenda")
                        .HasName("pk_venda");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_venda_id_cliente");

                    b.HasIndex("IdOperador")
                        .HasDatabaseName("ix_venda_id_operador");

                    b.HasIndex("IdPagamento")
                        .HasDatabaseName("ix_venda_id_pagamento");

                    b.ToTable("venda", (string)null);
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ClienteFisico", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ClienteFisico")
                        .HasForeignKey("NeyBaterias.Domain.Entities.ClienteFisico", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_fisico_cliente_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ClienteJuridico", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Cliente", "Cliente")
                        .WithOne("ClienteJuridico")
                        .HasForeignKey("NeyBaterias.Domain.Entities.ClienteJuridico", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cliente_juridico_cliente_id_cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.CompraReposicao", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("ComprasReposicao")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compra_reposicao_fornecedor_id_fornecedor");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Estoque", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.ItemReposicao", "ItemReposicao")
                        .WithOne("MovimentoEstoque")
                        .HasForeignKey("NeyBaterias.Domain.Entities.Estoque", "IdItemReposicao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_item_reposicao_id_item_reposicao");

                    b.HasOne("NeyBaterias.Domain.Entities.ItemVenda", "ItemVenda")
                        .WithOne("MovimentoEstoque")
                        .HasForeignKey("NeyBaterias.Domain.Entities.Estoque", "IdItemVenda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_item_venda_id_item_venda");

                    b.HasOne("NeyBaterias.Domain.Entities.Produto", "Produto")
                        .WithMany("MovimentosEstoque")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estoque_produto_id_produto");

                    b.Navigation("ItemReposicao");

                    b.Navigation("ItemVenda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ItemReposicao", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensReposicao")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_reposicao_produto_id_produto");

                    b.HasOne("NeyBaterias.Domain.Entities.CompraReposicao", "CompraReposicao")
                        .WithMany("ItensReposicao")
                        .HasForeignKey("IdReposicao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_reposicao_compra_reposicao_id_reposicao");

                    b.Navigation("CompraReposicao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Item", "Item")
                        .WithMany("ItensVenda")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_venda_item_id_item");

                    b.HasOne("NeyBaterias.Domain.Entities.Venda", "Venda")
                        .WithMany("ItensVenda")
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_venda_venda_id_venda");

                    b.Navigation("Item");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Produto", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Item", "Item")
                        .WithOne("Produto")
                        .HasForeignKey("NeyBaterias.Domain.Entities.Produto", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produto_item_id_item");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Servico", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Item", "Item")
                        .WithOne("Servico")
                        .HasForeignKey("NeyBaterias.Domain.Entities.Servico", "IdItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servico_item_id_item");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Venda", b =>
                {
                    b.HasOne("NeyBaterias.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venda_cliente_id_cliente");

                    b.HasOne("NeyBaterias.Domain.Entities.Operador", "Operador")
                        .WithMany("Vendas")
                        .HasForeignKey("IdOperador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venda_operador_id_operador");

                    b.HasOne("NeyBaterias.Domain.Entities.FormaPagamento", "FormaPagamento")
                        .WithMany("Vendas")
                        .HasForeignKey("IdPagamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venda_forma_pagamento_id_pagamento");

                    b.Navigation("Cliente");

                    b.Navigation("FormaPagamento");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("ClienteFisico");

                    b.Navigation("ClienteJuridico");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.CompraReposicao", b =>
                {
                    b.Navigation("ItensReposicao");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.FormaPagamento", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("ComprasReposicao");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Item", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("Produto");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ItemReposicao", b =>
                {
                    b.Navigation("MovimentoEstoque");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.ItemVenda", b =>
                {
                    b.Navigation("MovimentoEstoque");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Operador", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensReposicao");

                    b.Navigation("MovimentosEstoque");
                });

            modelBuilder.Entity("NeyBaterias.Domain.Entities.Venda", b =>
                {
                    b.Navigation("ItensVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
